### ISSUE TITLE
Video not showing up on mobile device Android/Chrome

### ISSUE THREAD

**Issue by hellvideorazor** [BlackSkorpio/OxyGen#114]
Uploaded Video does not show.
http://diehroptic.ch/koken/index.php?/albums/rathenower-rectimascope-48-2x/content/4-bladed/
Vimeo integrated works.
http://diehroptic.ch/koken/index.php?/albums/rathenower-rectimascope-48-2x/content/ja-spinn-i-denn/

**Comment by BlackSkorpio** [comment]
We will look into this.
But as it looks right now: the above video wont play while other videos do.
We tested this on Android running Chrome and it works.
http://diehroptic.ch/koken/index.php?/content/garage/

Lends me to believe that the problem resides in the above video it self

**Comment by BlackSkorpio** [comment]
The whole video part of OxyGen will have some work done to it self in version 3 that is in the works right now.

**Comment by hellvideorazor** [comment]
the video plays when watching through a desktop. Uplaoding it straight to my phone plays as well. the encoding is pretty standard.
Looking forward to a better video integration! feel free to ask me for beta testing ;)

**Comment by hellvideorazor** [comment]
another uploaded video (not vimeo) with slightly different encoding which works on my mobile: http://diehroptic.ch/content/sk-9mm/
so it might actually be related to encoding...

**Comment by BlackSkorpio** [comment]
I did suspect that since I cant replicate this issue anywhere else then with the video you pointed to at first.

Sorry to say: the applications for the BETA program is closed since a month back!

**Comment by BlackSkorpio** [comment]
But if your a member on the KCS forum, send me a PM there.
And I'll see what I can do...

**Comment by hellvideorazor** [comment]
it might be related to the strange aspect ratio. the encoding line was: ffmpeg -i /Volumes/LUMIX/DCIM/121_PANA/P1210014.MOV -vf hqdn3d=3:3:5:5,scale=1920:640,lut3d="Documents/VLogL_to_V709_forGH4_ver100_EN/VLog_to_V709_forV35_ver100.cube",unsharp,setsar=1:1,setdar=3:1 -c:v libx264 -preset fast -crf 21 -an Movies/45mm_f2.8_f8_scope__.mp4

**Comment by BlackSkorpio** [comment]
To be honest with you, that is not telling me anything hehe ;)

And OxyGen only shows the output from the Vimeo plugin: we are not doing anything with it (other then resize the video wrapper (.k-video.max-width-video-wrapper and .k-video) provided be the plugin/Koken

**Comment by hellvideorazor** [comment]
vimeo uploads do play fine. I just get the problem when I play direct to koken uploaded videos. And also not all of them are affected. How could I debug the player?

**Comment by hellvideorazor** [comment]
- thanks a lot for the help! much apreciated!

**Comment by BlackSkorpio** [comment]
The only way I can advice you is to take that with the Koken/NetObjects over at help.koken.me
Your welcome :D 
Glad to know that people is using my theme. :)

**Comment by BlackSkorpio** [comment]
BTW: You can see the v3 output for videos here, http://varoystrand.se/innehall/directions/

My site is running the latest snapshot of OxyGen :dart:
