### ISSUE TITLE
Categprie.lens shows no content

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#14]

**Comment by Hard-One** [comment]
Confirmed. Any idea why it just shows empty head and body tags? Seems category.lens is not parsed at all.

**Comment by BlackSkorpio** [comment]
I'm still looking in to this.
This is something that has been since the original Norma...

But I belive I got the solution in reach.

**Comment by Hard-One** [comment]
@BlackSkorpio I think I've got it.
