### ISSUE TITLE
Option to display title beneath the image in albums.lens

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#21]
display the "Img Info" on the albums but not on the images themselves?

**Comment by Hard-One** [comment]
Would be a great feature. Big like from me for this.

**Comment by BlackSkorpio** [comment]
Just made some testing locally 
Not as straight forward as one could belive

If adding the name below the image, every thing is pushed down...

**Comment by BlackSkorpio** [comment]
Solution could be to add a div as in the overlay today, but instead use a p-tag and position it along the bottom of the image

**Comment by BlackSkorpio** [comment]
@Hard-One Take a quick look at the above branch and give me comment...

**Comment by BlackSkorpio** [comment]
Extending this to albums.lens to

**Comment by Hard-One** [comment]
Looking good enough to merge it ;)

-----Original Message-----
