### ISSUE TITLE
Regular Navigation Current Item is shifted downwards in Firefox

### ISSUE THREAD

**Issue by Hard-One** [BlackSkorpio/OxyGen#27]
Using Firefox the navigation item of the current page is shifted downwards on some pages. IE is fine. 
Looks like this:
![shifted](https://cloud.githubusercontent.com/assets/11697267/9151192/35d97a66-3dfa-11e5-9716-b563eec00aaf.png)
But it should look like on the home page:
![normal](https://cloud.githubusercontent.com/assets/11697267/9151189/32c959a4-3dfa-11e5-8acd-a46e539bb533.png)

**Comment by BlackSkorpio** [comment]
Confirmed.

**Comment by Hard-One** [comment]
I think I got it. Not well tested though.

**Comment by BlackSkorpio** [comment]
Will, try to test it live tomorrow.
And if it's working as expected maybe push out a new release.

I owe you a beer.... ;)
