### ISSUE TITLE
Update notice

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#35]
Add some sort of notice in the users admin->Site when there is a update ready for OxyGen.

Should be possible by using koken:note
http://kokensupport.varoystrand.se/viewtopic.php?f=5&t=107
http://help.koken.me/customer/portal/questions/13016112-extending-koken-version-check-

**Comment by BlackSkorpio** [comment]
@Hard-One Could this be an option to include in OxyGen: https://github.com/cedced19/check-update-github ?

**Comment by Hard-One** [comment]
@BlackSkorpio What about the following? Some plain php using cURL. 

``` php
<?php
// Get cURL resource
$curl = curl_init();
// Set some options - we are passing in a useragent too here
curl_setopt_array($curl, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => 'https://api.github.com/repos/Koken-Community-Support/OxyGen/releases/latest',
    CURLOPT_USERAGENT => 'cURL Request'
));
// Send the request & save response to $resp
$resp = curl_exec($curl);
// Close request to clear up some resources
curl_close($curl);

$server = json_decode($resp);
$latest = $server->tag_name;
$client = "2.0.8"; // we have to fetch the current version here automatically...

if (!strcmp($latest, $client)) // compare strings and if update is available set variable to true
  $updateAvailable = true;
  else
    $updateAvailable = false;
    // dumping $latest to show that it's a string
    echo var_dump($latest);
?>
```

This will do it to get the version number of the latest release. Code could be shorter but for experimenting it'll do. :)

**Comment by BlackSkorpio** [comment]
Looks pretty good! :)
I'm trusting you on this one... ;)

Will add some "koken code" to display it in a koken:note

**Comment by Hard-One** [comment]
I'll take over this issue ;) I think I'm close to it...

**Comment by BlackSkorpio** [comment]
Handing it over with warm hands ;)

Keep it open until we are 100% sure on the solution is working: or we abandon the idea...

**Comment by BlackSkorpio** [comment]
What you think, will this one make it into 2.1
Or should we let it come whenever it's ready?

**Comment by Hard-One** [comment]
2.1 ;)
I'll do the code and you could take a look when it comes to styling. :D

**Comment by BlackSkorpio** [comment]
No problem:)

**Comment by Hard-One** [comment]
@BlackSkorpio I'm ready. :)

**Comment by BlackSkorpio** [comment]
Added some "minor" styling to the whole thing...
Test it and tell me if it is a "grabber" or "no go"
Also removed the "no update" and added variable for the download link

**Comment by Hard-One** [comment]
@BlackSkorpio Major breakthrough! Slowly koken's API starts to make sense^^

Had some thoughts about styling the box. Not a top priority issue but I think the donationbox and the update box should be styled quite similar. Maybe we only need to change the background to a decent highlighting color. What do you think?

**Comment by BlackSkorpio** [comment]
Well, we are using undocumented variables ;)
So no wonder things aren't clear as glass hehe

Regarding the donationbox: been thinking along the same lines, but the two are performing two different "tasks" so we can't have them identical...
That's a big "no no" in UI design hehe

But your right we need to modify the donationbox, so it is at least following the rest of the design....
Will add it to the issue tracker as a reminder ;) and see what I can come up with :)

What do you think is the update notifier ready to be merged in to dev?

**Comment by Hard-One** [comment]
That's why I would make the background color of the updatebox red. Make them unique in color, but the basic look and feel can be identical.

IMHO we should get the style done before merging into dev.

**Comment by Hard-One** [comment]
Just want to make clear: I like the style of the donationbox. Actually I'm not satisfied with the style of the updatebox.

**Comment by BlackSkorpio** [comment]
I see how your thinking, but I have to disagree with you here ;)
Red is a "high-alert" color...
I'm more for making the h1 in "pure" red.
That way we have a "middle ground" in sort... ;)

What is "bugging" you with the updatebox?
Maybe ad a option to dismiss it to next update is available?

**Comment by Hard-One** [comment]
Red was just an example ;) Thinking about it longer makes me thinking about OxyGen-blue ;D
The updatebox is to sharp edged and bulky. The donationbox looks much smoother and integrates better into the design of the dashboard.
Adding an option to dismiss is a nice idea. We should make it it's own issue, as I have no idea how to implement this quickly.

**Comment by BlackSkorpio** [comment]
Making it more "blueish" is a good idea! :+1: 
I'll add some shadow to the box, as in the donationbox...
That will make "smoother" and blend in better :)

I didn't mean to implement the "dismiss feature" now... Hehe
To make this "meaningful" we need to set a cookie and check it together with the version... ;)
So that's something we can keep for the future to think about (when we are out of other ideas) hehe

**Comment by BlackSkorpio** [comment]
It just hit me!!!!!!!

I'll use the OxyGen preview image, for the updatebox: as an background!?
That way we are keeping the OxyGen blue "all the way" :)

**Comment by Hard-One** [comment]
Sounds really good! And softening with a shadow, too.

You really think we will run out of ideas??? :D Yeah, let's make it an issue with a milestone "future"?

**Comment by BlackSkorpio** [comment]
Decided then :+1:  :)

Haha, no: that's not a big risk haha

Jupp, its definitely a milestone feature :)

**Comment by BlackSkorpio** [comment]
Will "fix" this tomorrow:) since the GF demands to be entertained in front of the "telly" tonight

**Comment by BlackSkorpio** [comment]
@Hard-One Pushed up some design updates...
A "goer", or a "no-goer"?

**Comment by Hard-One** [comment]
I'll close this issue, as things are working and styled as expected. Well done @BlackSkorpio :)

**Comment by BlackSkorpio** [comment]
Well Done @Hard-One 
Without your work, there would not be any design:)

**Comment by Hard-One** [comment]
can we push fixing-#35 to develop? Someone made some commits to that branch not related to #35

Or maybe I'm just daft^^

**Comment by BlackSkorpio** [comment]
Push it over :) :+1: 

"Did I do THAT?" :/
