### ISSUE TITLE
Add categories to essays.lens

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#39]
Show related categories for essay

**Comment by BlackSkorpio** [comment]
@Hard-One could this work as a category icon?
![image](https://cloud.githubusercontent.com/assets/11587201/9536357/2d413304-4d2b-11e5-9d78-63b6c2d3e9bf.jpg)

**Comment by Hard-One** [comment]
@BlackSkorpio I always find it  difficult to find meaningful icons. My first thought would be an album or folder. Googling a bit brought me to something like this.
![category](https://cloud.githubusercontent.com/assets/11697267/9547449/dffb88ae-4d9a-11e5-8868-b5b489013a72.png)
I like the handdrawn style of your icon. I guess that was not really helpul, was it? ;)

**Comment by BlackSkorpio** [comment]
Looked at that one too;)
But it is a bit "off" since it is square:/

Well, it will be one of these two 
Will experiment with them and see witch is best output wise

On the same time, I will Need to find a nice way to display the cats, so they don't clutter the UI.
