### ISSUE TITLE
Displays a blank page when leaving lightbox in internet explorer 

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#4]
When closing lightbox ie displays a blank page instead of the content.

**Comment by BlackSkorpio** [comment]
Cant verify this...
So i need some help from IE users

**Comment by Hard-One** [comment]
Can't verify this in IE 11. I think you can close this issue.

**Comment by BlackSkorpio** [comment]
Thnx: :)
