### ISSUE TITLE
Donationsbox not show when there is no slideshow

### ISSUE THREAD

**Issue by Hard-One** [BlackSkorpio/OxyGen#47]

**Comment by BlackSkorpio** [comment]
So when no images are found in the selected pulse source koken:note is not showing?

**Comment by Hard-One** [comment]
Correct and I've pushed the fix to the wrong branch :/

**Comment by BlackSkorpio** [comment]
Ahhh, noticed now...
Revert the commit... :)
And push it in the right place: or just leave it and will merge it in to dev?

**Comment by Hard-One** [comment]
Done. Pushed to develop as it needs no vetting and should be stable enough for develop. ;)

**Comment by BlackSkorpio** [comment]
Agreed:)
