### ISSUE TITLE
Categories loop need an icon

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#50]
Need to ad an icon to the category loop

**Comment by BlackSkorpio** [comment]
See #39

**Comment by BlackSkorpio** [comment]
Got it nailed down to three contenders!....
![cats1](https://cloud.githubusercontent.com/assets/11587201/9577720/121ceaf8-4fe4-11e5-97da-9fb3dcf22bbf.png)
![cats2](https://cloud.githubusercontent.com/assets/11587201/9577722/121ed5e8-4fe4-11e5-8204-1f1f0b4781fe.PNG)
![cats3](https://cloud.githubusercontent.com/assets/11587201/9577721/121e5ae6-4fe4-11e5-84d7-9cb322b01c75.PNG)

Need your vote @Hard-One

**Comment by Hard-One** [comment]
Please don't bash me ;)

Icon number two is the one telling me, that it's a category. maybe the color should be the same as the tag icon? Would make the look more consistent. Number one still looks like an album to me and number three looks like essays or documents.

**Comment by BlackSkorpio** [comment]
I'm actually leaning towards the third one.
Since people that are not geeks like me and you are choosing that one!...

My personal "fav" was/is number one hehe

This round is neither of us "winning" as it looks...

Well, it's a quick edit too change it in settings.css.lens hehe

**Comment by Hard-One** [comment]
I'm ok with it. :)

**Comment by BlackSkorpio** [comment]
:) :+1:
