### ISSUE TITLE
Design changes for the updatebox

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#51]
Add the preview image as an background
Add a box shadow 
Change the H1 to pure red

**Comment by BlackSkorpio** [comment]
Reminder: for the background 
https://css-tricks.com/snippets/css/transparent-background-images/

**Comment by BlackSkorpio** [comment]
Better @Hard-One ?

**Comment by Hard-One** [comment]
A lot better :) Really like it now. Good job!

**Comment by BlackSkorpio** [comment]
Thnx :)
