### ISSUE TITLE
Change to the GitHub rep dir structure 

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#52]
To make sure that we avoid periods (.) in the downloads from GitHub I'm proposing that we move the entire repository to a directory I.e OxyGen

That way we can avoid the Koken bug where a period in the theme dir will get Koken not to load the theme in admin
The downloaded archive would get the structure:

<pre>[oxygen-2.1]
    README.MD
    LICENSE 
    [OxyGen]
        [css]
        [fonts]
        [inc]
</pre>

Thus ensuring a consistent theme dir name, and avoiding periods in the same. 

What do you think about this @Hard-One ?

**Comment by BlackSkorpio** [comment]
What you think @Hard-One

**Comment by Hard-One** [comment]
This needs some major thoughts. I am not yet familiar with building releases on github, but there must be a way to build cleaned up downloads. I see that everywhere on git but I don't know how to do that. :(

We should not provide .gitignore and other files to users not collaborating to the repo.

**Comment by BlackSkorpio** [comment]
From what i can read in https://help.github.com/articles/creating-releases/ there is no way to avoid the [foo-2.1.0] naming: not without doing as described above.

The idea comes from other Koken devs that started to implement the above structure for there plugins.

**Comment by Hard-One** [comment]
This affects only the name of the .zip file? Then I'd say that's not an issue. What I mean is to remove (or not adding) dot-files and other files not meant to be in a release zip file.

-----Original Message-----

**Comment by BlackSkorpio** [comment]
It will only affect the Name of the zip file (and the structure)
All files not part of the theme will stay at the root of the repository 
Gitignore and such are left in the root
Thus giving us a clean theme dir with a predefined name of our choice [OxyGen]

**Comment by BlackSkorpio** [comment]
@Hard-One Just pushed a new branch with the suggested structure

**Comment by BlackSkorpio** [comment]
If it looks ok, push it to development, and we have a full release again! :)

**Comment by Hard-One** [comment]
Will check if it breaks my eclipse/xampp setup ;)

**Comment by BlackSkorpio** [comment]
Haha, it will probably do... ;) :P

**Comment by Hard-One** [comment]
Yeah, it does :(

**Comment by BlackSkorpio** [comment]
Hmmm
How?...

**Comment by Hard-One** [comment]
Well, my setup is the following. Inside my htdocs is a clean koken installation, inside storage/themes/ is the working drectory from eclipse. This worked well, as it's the root of the theme. Now theme path is storage/themes/OxyGen/OxyGen

**Comment by BlackSkorpio** [comment]
Ahhhh....
I suspected something like that... :(

Maybe better to revert back?
And hold this structure change?

**Comment by Hard-One** [comment]
Just have to find out how to properly setup my environement ;) That's one reason why I mentioned that it needs some deeper thoughts.

**Comment by BlackSkorpio** [comment]
Well, we revert it: for now
And putting on our thinking caps ;)

Can you revert it?
My GF demands a game of backgammon "right now"....

**Comment by Hard-One** [comment]
Keep the branch as it is. Working on other branches makes no trouble. It's just an issue with my setup. I'm pretty sure that I have not set it up in a best practice manner. Still learning ;)

**Comment by BlackSkorpio** [comment]
Same here hehe
Not used to collaborate in GitHub ;)

So, should we set the structure in other words?

**Comment by BlackSkorpio** [comment]
Im working the old fashioned way: with a plain text editor hehe
And does not even have my GitHub dir pointed to my XAMP!

**Comment by Hard-One** [comment]
I think this should make it into 2.1.

**Comment by BlackSkorpio** [comment]
I'm all for this :)

**Comment by Hard-One** [comment]
Just merged this into develop. ;)
