### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#55]
Documentation needs to be updated!
Nothing done there since 2.0? :-1: 
http://varoystrand.se/sidor/oxygen/

**Comment by Hard-One** [comment]
Maybe we should think about hosting or mirroring the documentation on github (Wiki) or hosting inside http://kokensupport.varoystrand.se/ ?

**Comment by BlackSkorpio** [comment]
I'm thinking along the same lines: and then i can keep the pages on varoystrand.se updated...

**Comment by Hard-One** [comment]
Maybe there is an API to pull the wiki from github to varoystrand?

**Comment by BlackSkorpio** [comment]
Probably... :+1: 
But that is something for the future: when we dont have any "better ideas" to explore haha

**Comment by BlackSkorpio** [comment]
What do you think Wiki on KCS, as this:
http://kokensupport.varoystrand.se/app.php/wiki
Or host it in the Wiki here?

## Pros/Cons

### KCS

:+1: On KCS there is no need for a second account
:+1:WYSIWYG text editor
:+1:Simple to use for members
:+1:"Everything" gathered on the same place
:+1:Group policy's already in action
:+1:Can set access permissions down to user level
:+1:It can be extended to höst other devs documentation 

---

:-1:Not a full featured Wiki
:-1:Still in "beta/develop" stage

### GitHub

:+1:Full featured Wiki
:+1:Powerful 
:+1:Possible to integrate with the "organization"
:+1:We can tie it together with the issue tracker

---

:-1: Users need a GitHub account 
:-1:We are forcing members away from KCS
:-1:Harder to use initially 

Some more pros/cons?...
I'm all ears :+1:
