### ISSUE TITLE
Breadcrumps in some lens files

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#56]
Find and isolate the lens files where we need/can use breadcrups to make life easier for the visitors: ie <pre>categoriers.lens, category.lens, tags.lens, tag.lens, timeline.lens, error.lens, favorites.lens, map.lens</pre> is what comes to mind first
https://github.com/Koken-Community-Support/OxyGen/tree/Breadcrump-nav

**Comment by Hard-One** [comment]
Sounds good. Should be optional to switch on or off from dashboard. Btw. your posted link leads to nirvana. ;)

**Comment by BlackSkorpio** [comment]
Nirvana?... ;)

Option to enable/disable both breadcrumps and tags/cats will come :)

**Comment by BlackSkorpio** [comment]
But not for 2.1 haha

**Comment by Hard-One** [comment]
Overlooked the branch. Sorry.

**Comment by BlackSkorpio** [comment]
Haha no problem :+1:
