### ISSUE TITLE
timeline.lens needs some major work

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#57]
The output in timeline.lens needs some work
This is a totaly forgotten part of the site!
koken:link needs to be added in a couple of places
different the output between ordinary albums and sets needs to be done
Different image-presets per album/set and ordinary image
categories and tags also need to be added to the output
https://github.com/Koken-Community-Support/OxyGen/tree/Timeline-fix

**Comment by Hard-One** [comment]
Yeah, a lot of work to do. Do you already have some ideas or even a wireframe?

**Comment by BlackSkorpio** [comment]
I'm working on right now...
Almost finished!
http://varoystrand.se/tidslinje/
Need to also edit info.json so timeline listens to "open in lightbox" settings ;)

(its a rainy day here...)

**Comment by Hard-One** [comment]
Do you have any sets in your timeline?

**Comment by BlackSkorpio** [comment]
Not on my live site.... :(

(got to love my self for doing development on my live site! :dash: )

Do you?

**Comment by BlackSkorpio** [comment]
Here is the branch: https://github.com/Koken-Community-Support/OxyGen/tree/Timeline-fix

**Comment by Hard-One** [comment]
As a fan of best practice behaviour I never develop on a live site, not even on a server hosting live sites.

**Comment by BlackSkorpio** [comment]
_Putting my self in the corner_ hehe

Well, i "know all that" and been bashing people for doing it (when things goes wrong): but...
It was easy (this time around) haha :dancers:

**Comment by BlackSkorpio** [comment]
This takes care of the timeline: https://github.com/Koken-Community-Support/OxyGen/tree/Timeline2
