### ISSUE TITLE
Naming convention of translated UI 

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#60]
We need to change the naming conventions for the translated UI.
Ie move away from using "name": "OxyGen-de" since this will the translated OxyGen not to be recognized by PhotSwipe automatically.
Instead I think we should be using: "version": "2.1.0-de"

And start using the correct ISO codes for the languages...
https://github.com/Koken-Community-Support/OxyGen/wiki/Language-ISO-Codes

The move from "name" to "version" should be done in 2.1.0?

**Comment by Hard-One** [comment]
Every translated interface will be in a separate branch and all branches are released together in a single release, so there is no need for separate versions.
