### ISSUE TITLE
German_UI needs an update

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#91]
The German_UI branch contains english strings since 2.1!

**Comment by BlackSkorpio** [comment]
Files affected:
- [x] inc/components/album_cover.html #10
- [x] inc/components/album_cover_text.html #10
- [x] album.lens #14
- [x] albums.lens #7
- [x] category.lens #6
- [x] content.lens #11
- [x] contents.lens #17
- [x] index.lens #65
- [x] tag.lens #9

**Comment by Hard-One** [comment]
Now I am embarassed... will fix it soon. Sorry for any inconvenience.

-----Original Message-----

**Comment by BlackSkorpio** [comment]
:+1:  :dancers:

**Comment by Hard-One** [comment]
Been there, done that...
